[package]
name = "termtris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22"
rand = "0.8.5"
tokio = "1.17.0"
tui = "0.17.0"
